[
  {
    "id": 1,
    "title": "Auriculares Inalámbricos Bluetooth con Cancelación de Ruido",
    "category": "Tecnología",
    "description": "Auriculares de alta fidelidad de sonido con batería de hasta 30 horas de reproducción continua y cancelación activa de ruido.",
    "price": 29.99,
    "currency": "USD",
    "rating": 4.8,
    "discount": 30,
    "store": "Amazon",
    "plan": "global",
    "region": "Internacional",
    "imageUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80",
    "videoUrl": "https://www.youtube.com/embed/2-i_nK_aGv8",
    "affiliateUrl": "https://amazon.com"
  },
  {
    "id": 2,
    "title": "Chaqueta Camisa Estampada de Moda Casual para Hombre",
    "category": "Ropa",
    "description": "Excelente chaqueta de diseño casual y corte moderno. Tela suave, fresca y resistente ideal para uso diario.",
    "price": 18.50,
    "currency": "USD",
    "rating": 4.5,
    "discount": 15,
    "store": "Shein",
    "plan": "global",
    "region": "Internacional",
    "imageUrl": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&auto=format&fit=crop&q=80",
    "videoUrl": null,
    "affiliateUrl": "https://shein.com"
  },
  {
    "id": 3,
    "title": "Reloj Inteligente Deportivo con Monitor de Ritmo Cardíaco",
    "category": "Electrónica",
    "description": "Smartwatch resistente al agua con lectura de frecuencia cardíaca, contador de pasos, GPS integrado y notificaciones en tiempo real.",
    "price": 12.99,
    "currency": "USD",
    "rating": 4.3,
    "discount": 50,
    "store": "AliExpress",
    "plan": "global",
    "region": "Internacional",
    "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80",
    "videoUrl": "https://assets.mixkit.co/videos/preview/mixkit-smartwatch-close-up-42805-large.mp4",
    "affiliateUrl": "https://aliexpress.com"
  },
  {
    "id": 4,
    "title": "Lote x100 Fundas de Silicona Transparentes para Smartphone",
    "category": "Mayorista",
    "description": "Paquete al mayor de estuches antigolpes transparentes ultrarresistentes para múltiples modelos de teléfonos inteligentes.",
    "price": 45.00,
    "currency": "USD",
    "rating": 4.9,
    "discount": 20,
    "store": "Alibaba",
    "plan": "global",
    "region": "Internacional",
    "imageUrl": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=500&auto=format&fit=crop&q=80",
    "videoUrl": null,
    "affiliateUrl": "https://alibaba.com"
  },
  {
    "id": 5,
    "title": "Zapatos Deportivos Casuales de Cuerina Duradera",
    "category": "Calzado",
    "description": "Calzado cómodo y duradero disponible en todas las tallas. Envíos a nivel nacional directos al comprador.",
    "price": 35.00,
    "currency": "USD",
    "rating": 4.7,
    "discount": 10,
    "store": "Detal",
    "plan": "nacional",
    "region": "Caracas",
    "imageUrl": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80",
    "videoUrl": null,
    "affiliateUrl": "https://wa.me/1234567890"
  },
  {
    "id": 6,
    "title": "Servicio de Mantenimiento y Reparación de Computadoras",
    "category": "Servicios",
    "description": "Soporte técnico profesional en sitio y remoto. Diagnóstico gratuito, formateo, instalación de software y limpieza de componentes.",
    "price": 25.00,
    "currency": "USD",
    "rating": 5.0,
    "discount": 0,
    "store": "Servicios",
    "plan": "local",
    "region": "Valencia",
    "imageUrl": "https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=500&auto=format&fit=crop&q=80",
    "videoUrl": null,
    "affiliateUrl": "https://wa.me/1234567890"
  }
]
